### PR TITLE
Update dependency from nuxt-simple-sitemap to @nuxtjs/sitemap

### PR DESCRIPTION
**Pull request by Abdallah-Awwad**
The nuxt-simple-sitemap package has been deprecated and migrated to @nuxtjs/sitemap. 
See: https://www.npmjs.com/package/nuxt-simple-sitemap

Fixes: https://github.com/directus-labs/agency-os/issues/86

### CODE REVIEW

**Comment by sergiocbueno** [comment]
Thanks! This dependency fix works like a charm for me.

**Comment by Abdallah-Awwad** [comment]
@sergiocbueno, Glad it helped! 🤩

**Review by omgitsjan — COMMENTED** [review]
lgtm 👍

**Review by ComfortablyCoding — APPROVED** [review]
LGTM 🚀

**Pull request merged**
